#!/usr/bin/env bash
set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "dev" ]; then
    echo "Error: You are not on the correct branch. Aborting."
    exit 1
fi

git add -A

if [[ -z $1 ]]; then
    git commit -m Update
else
    git commit -m "$1"
fi

git push origin dev

git switch master
git merge -Xtheirs dev -m "Merge branch 'dev'"

python -B summary.py
python -B normalize_img_links.py

set +e

git add -A
git commit -m Update
git push origin master

git switch dev
